<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260110213636 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article_project (article_id INT NOT NULL, project_id INT NOT NULL, PRIMARY KEY (article_id, project_id))');
        $this->addSql('CREATE INDEX IDX_C26194597294869C ON article_project (article_id)');
        $this->addSql('CREATE INDEX IDX_C2619459166D1F9C ON article_project (project_id)');
        $this->addSql('CREATE TABLE media_object (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE article_project ADD CONSTRAINT FK_C26194597294869C FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_project ADD CONSTRAINT FK_C2619459166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE project ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE article_project DROP CONSTRAINT FK_C26194597294869C');
        $this->addSql('ALTER TABLE article_project DROP CONSTRAINT FK_C2619459166D1F9C');
        $this->addSql('DROP TABLE article_project');
        $this->addSql('DROP TABLE media_object');
        $this->addSql('ALTER TABLE article DROP updated_at');
        $this->addSql('ALTER TABLE project DROP updated_at');
    }
}
